name: Simple Python HTTP Server

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: apt update && apt install -y emacs
      - name: Run tests
        run: test/test.sh
