name: uniq

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
      options: --tty
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: apt update && apt install -y emacs sbcl
      - name: Run tests
        run: test/test.sh
